### ISSUE TITLE
Cannot find type 'Option' in scope

### ISSUE THREAD

**Issue by fatihdurmaz** [Inxel/CustomizableSegmentedControl#4]
import SwiftUI
import CustomizableSegmentedControl

struct MovieView: View {
    
    @State private var selection: Option = .first -> this error
    
    var body: some View {
        VStack {

            CustomizableSegmentedControl(
                selection: $selection,
                options: [.one, .two, .three],
                insets: .init(top: 4, leading: 4, bottom: 4, trailing: 4),
                interSegmentSpacing: 2,
                contentStyle: .withBlendMode(),
                animation: .default,
                selectionView: {
                    Color.white
                        .clipShape(RoundedRectangle(cornerRadius: 10))
                },
                segmentContent: { option, isPressed in
                    HStack(spacing: 4) {
                        Text(option.title)
                            .font(.system(size: 16, weight: .semibold, design: .rounded))

                        option.imageName.map(Image.init(systemName:))
                    }
                    .foregroundColor(.white.opacity(isPressed ? 0.7 : 1))
                    .lineLimit(1)
                    .padding(.vertical, 10)
                    .padding(.horizontal, 12)
                    .frame(maxWidth: .infinity)
                }
            )
            .background(Color.blue)
            .clipShape(RoundedRectangle(cornerRadius: 14))

        }
    }
}
Cannot find type 'Option' in scope

**Comment by Inxel** [comment]
You should implement `Hashable` & `Identifiable` struct or enum for selection option yourself.

**Comment by fatihdurmaz** [comment]
How to initilaze

**Comment by Inxel** [comment]
You need to create object in global scope or `MovieView` scope. For example:
```
extension MovieView {

    enum Option: String, Identifiable, Hashable {
        case first
        case second
        case third

        var id: String { rawValue }
        var title: String { rawValue.capitalized }
        var imageName: String? {
            switch self {
                case .first, .third:
                    return nil
                case .second:
                    return "suit.heart.fill"
            }
        }
    }

}
```

**Comment by fatihdurmaz** [comment]
It will be more understandable if you add this part to the readme file of the package. Thank you.
